# Generated by Django 4.1.7 on 2023-02-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
