# Generated by Django 4.1.7 on 2023-02-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0002_blog_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('create_add', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
