# Generated by Django 4.1.6 on 2023-02-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/logo', verbose_name='Лого')),
                ('title', models.CharField(max_length=30, verbose_name='Название Сервиса')),
                ('description', models.TextField(max_length=50, verbose_name='Описание')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Сервисы',
            },
        ),
    ]
