# Generated by Django 4.1.6 on 2023-02-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/logo', verbose_name='Фото')),
                ('title', models.CharField(max_length=30, verbose_name='Название Плана')),
                ('description', models.TextField(max_length=50, verbose_name='Описание')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'План',
            },
        ),
    ]
