# Generated by Django 4.1.6 on 2023-02-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1, max_length=250, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
