# Generated by Django 4.1.7 on 2023-02-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('adres', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Контакт',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Rewiews',
        ),
    ]
