# Generated by Django 4.1.7 on 2023-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_contact_image1_contact_image2_contact_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/logo')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/logo', verbose_name='Фото')),
                ('title', models.CharField(max_length=30, verbose_name='Название Плана')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'План',
            },
        ),
        migrations.CreateModel(
            name='Rewiews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
