# Generated by Django 4.1.7 on 2023-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_category_plan_rewiews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='rewiews',
            name='deviz',
            field=models.TextField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='rewiews',
            name='image',
            field=models.ImageField(null=True, upload_to='movie/image_user'),
        ),
        migrations.AddField(
            model_name='rewiews',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewiews',
            name='prof',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
