# Generated by Django 4.1.7 on 2023-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_delete_employee_rewiews_deviz_rewiews_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='fulltext',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='imagefull',
            field=models.ImageField(null=True, upload_to='media/services/image'),
        ),
    ]
